name: ci

on: push

env:
  IMAGE_REGISTRY: "ghcr.io"
  REGISTRY_USER: "${{ github.repository_owner }}"
  REGISTRY_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  IMAGE_REPO: "ghcr.io/${{ github.repository_owner }}"
  IMAGE_NAME: "folly-dev-env"
  DEBIAN_FRONTEND: noninteractive
  IMAGE_TAG: 0.0.1 

jobs:
  build:
    runs-on: ubuntu-20.04
    container: 
      image: ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Compile and Run
        run: |
          make configure
          make build
          make run
          # make bench
