name: ci

on: push

env:
  DEBIAN_FRONTEND: noninteractive


jobs:
  build:
    runs-on: ubuntu-20.04

    container: 
      image: ghcr.io/ren15/folly-dev-env:0.0.1

    steps:
      - uses: actions/checkout@v2
      
      - name: Compile and Run
        run: |
          ninja --version
          make configure
          make build
          make run
          # make bench
