name: container_build

on: push

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: build container
        run: |
          cd ci/container
          cp ../*.sh .
          pwd && ls
          docker build -t test .
