name: create_image

on:
  push:
    paths:
      - 'ci/**'
      - '.github/workflows/create_image.yml'

env:
  IMAGE_REGISTRY: "ghcr.io"
  REGISTRY_USER: "${{ github.repository_owner }}"
  REGISTRY_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  IMAGE_REPO: "ghcr.io/${{ github.repository_owner }}"
  IMAGE_NAME: "folly-dev-env"
  DEBIAN_FRONTEND: noninteractive
  IMAGE_TAG: 0.0.3

jobs:
  create_image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Login docker
        run: |
          echo ${{ env.REGISTRY_TOKEN }} | docker login ${{ env.IMAGE_REGISTRY }} -u ${{ env.REGISTRY_USER }} --password-stdin

      - name: build container
        run: |
          cd ci/container
          cp ../*.sh .
          pwd && ls
          docker build -t ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
          
      - name: Push docker image
        run: |
          docker push ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}